# = Redmine configuration file
#
# Each environment has it's own configuration options.  If you are only
# running in production, only the production block needs to be configured.
# Environment specific configuration options override the default ones.
#
# Note that this file needs to be a valid YAML file.
# DO NOT USE TABS! Use 2 spaces instead of tabs for identation.

# default configuration options for all environments
default:
  # Outgoing emails configuration
  # See the examples below and the Rails guide for more configuration options:
  # http://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration
  email_delivery:
    delivery_method: :{{SMTP_METHOD}}
    {{SMTP_METHOD}}_settings:
      enable_starttls_auto: {{SMTP_STARTTLS}}
      address: "{{SMTP_HOST}}"
      port: {{SMTP_PORT}}
      domain: "{{SMTP_DOMAIN}}"
      authentication: {{SMTP_AUTHENTICATION}}
      user_name: "{{SMTP_USER}}"
      password: "{{SMTP_PASS}}"
      openssl_verify_mode: "{{SMTP_OPENSSL_VERIFY_MODE}}"
      ca_path: "{{SMTP_CA_PATH}}"
      ca_file: "{{SMTP_CA_FILE}}"
      tls: {{SMTP_TLS}}

  # Absolute path to the directory where attachments are stored.
  # The default is the 'files' directory in your Redmine instance.
  # Your Redmine instance needs to have write permission on this
  # directory.
  # Examples:
  attachments_storage_path: {{REDMINE_ATTACHMENTS_DIR}}

  # Configuration of the autologin cookie.
  autologin_cookie_name: {{REDMINE_AUTOLOGIN_COOKIE_NAME}}
  autologin_cookie_path: {{REDMINE_AUTOLOGIN_COOKIE_PATH}}
  autologin_cookie_secure: {{REDMINE_AUTOLOGIN_COOKIE_SECURE}}

  # Configuration of SCM executable command.
  scm_subversion_command: svn
  scm_mercurial_command: hg
  scm_git_command: git
  scm_cvs_command: cvs
  scm_bazaar_command: bzr
  scm_darcs_command: darcs

  # SCM paths validation.
  #
  # You can configure a regular expression for each SCM that will be used to
  # validate the path of new repositories (eg. path entered by users with the
  # "Manage repositories" permission and path returned by reposman.rb).
  # The regexp will be wrapped with \A \z, so it must match the whole path.
  # And the regexp is case sensitive.
  #
  # You can match the project identifier by using %project% in the regexp.
  #
  # You can also set a custom hint message for each SCM that will be displayed
  # on the repository form instead of the default one.
  #
  # Examples:
  # scm_subversion_path_regexp: file:///svnpath/[a-z0-9_]+
  # scm_subversion_path_info: SVN URL (eg. file:///svnpath/foo)
  #
  # scm_git_path_regexp: /gitpath/%project%(\.[a-z0-9_])?/
  #
  # scm_subversion_path_regexp:
  # scm_mercurial_path_regexp:
  # scm_git_path_regexp:
  # scm_cvs_path_regexp:
  # scm_bazaar_path_regexp:
  # scm_darcs_path_regexp:
  # scm_filesystem_path_regexp:

  # Absolute path to the SCM commands errors (stderr) log file.
  # The default is to log in the 'log' directory of your Redmine instance.
  scm_stderr_log_file: {{REDMINE_LOG_DIR}}/redmine/redmine_scm_stderr.log

  # Key used to encrypt sensitive data in the database (SCM and LDAP passwords).
  # If you don't want to enable data encryption, just leave it blank.
  # WARNING: losing/changing this key will make encrypted data unreadable.
  #
  # If you want to encrypt existing passwords in your database:
  # * set the cipher key here in your configuration file
  # * encrypt data using 'rake db:encrypt RAILS_ENV=production'
  #
  # If you have encrypted data and want to change this key, you have to:
  # * decrypt data using 'rake db:decrypt RAILS_ENV=production' first
  # * change the cipher key here in your configuration file
  # * encrypt data using 'rake db:encrypt RAILS_ENV=production'
  # database_cipher_key:

  # Set this to false to disable plugins' assets mirroring on startup.
  # You can use `rake redmine:plugins:assets` to manually mirror assets
  # to public/plugin_assets when you install/upgrade a Redmine plugin.
  #
  mirror_plugins_assets_on_startup: true

  # Your secret key for verifying cookie session data integrity. If you
  # change this key, all old sessions will become invalid! Make sure the
  # secret is at least 30 characters and all random, no regular words or
  # you'll be exposed to dictionary attacks.
  #
  # If you have a load-balancing Redmine cluster, you have to use the
  # same secret token on each machine.
  #secret_token: 'change it to a long random string'

  # Requires users to re-enter their password for sensitive actions (editing
  # of account data, project memberships, application settings, user, group,
  # role, auth source management and project deletion). Disabled by default.
  # Timeout is set in minutes.
  #
  sudo_mode: {{REDMINE_SUDO_MODE_ENABLED}}
  sudo_mode_timeout: {{REDMINE_SUDO_MODE_TIMEOUT}}

  # Absolute path (e.g. /usr/bin/convert, c:/im/convert.exe) to
  # the ImageMagick's `convert` binary. Used to generate attachment thumbnails.
  imagemagick_convert_command: /usr/bin/convert

  # Configuration of RMagick font.
  #
  # Redmine uses RMagick in order to export gantt png.
  # You don't need this setting if you don't install RMagick.
  #
  # In CJK (Chinese, Japanese and Korean),
  # in order to show CJK characters correctly,
  # you need to set this configuration.
  #
  # Because there is no standard font across platforms in CJK,
  # you need to set a font installed in your server.
  #
  # This setting is not necessary in non CJK.
  # rmagick_font_path:

  # Maximum number of simultaneous AJAX uploads
  max_concurrent_ajax_uploads: {{REDMINE_CONCURRENT_UPLOADS}}

  # Configure OpenIdAuthentication.store
  #
  # allowed values: :memory, :file, :memcache
  openid_authentication_store: :memory

  # Path to store backups (docker-redmine only)
  backup_storage_path: {{REDMINE_BACKUPS_DIR}}
  backup_expiry: {{REDMINE_BACKUP_EXPIRY}}

# specific configuration options for production environment
# that overrides the default ones
production:

# specific configuration options for development environment
# that overrides the default ones
development:
