#!/bin/bash
## Script to generate backup of running Redmine instance from the BASH shell

set -e
source ${REDMINE_RUNTIME_DIR}/functions

install_themes

# Restart unicorn
supervisorctl restart unicorn
