#!/bin/bash
## Script to install themes on a running Redmine instance from the BASH shell

set -e
source ${REDMINE_RUNTIME_ASSETS_DIR}/functions

install_themes

# Restart puma
supervisorctl restart puma
