#!/bin/bash
## Script to install plugins on a running Redmine instance from the BASH shell

set -e
source ${REDMINE_RUNTIME_ASSETS_DIR}/functions

install_plugins

# Restart puma
supervisorctl restart puma
