#!/bin/bash
set -e

# http://redminecrm.com/pages/a1-theme
A1_VERSION=1_1_2
if [ -f ${THEMES_SETUP_DIR}/a1-${A1_VERSION}.zip ]; then
  unzip ${THEMES_SETUP_DIR}/a1-${A1_VERSION}.zip -d ${THEMES_INSTALL_DIR}/
else
  wget http://redminecrm.com/license_manager/7644/a1-${A1_VERSION}.zip -P /tmp/
  unzip /tmp/a1-${A1_VERSION}.zip -d ${THEMES_INSTALL_DIR}/
  rm -rf /tmp/a1-${A1_VERSION}.zip
fi

# http://www.redminecrm.com/pages/coffee-theme
COFFEE_VERSION=0_0_4
if [ -f ${THEMES_SETUP_DIR}/coffee-${COFFEE_VERSION}.zip ]; then
  unzip ${THEMES_SETUP_DIR}/coffee-${COFFEE_VERSION}.zip -d ${THEMES_INSTALL_DIR}/
else
  wget http://www.redminecrm.com/license_manager/4508/coffee-${COFFEE_VERSION}.zip -P /tmp/
  unzip /tmp/coffee-${COFFEE_VERSION}.zip -d ${THEMES_INSTALL_DIR}/
  rm -rf /tmp/coffee-${COFFEE_VERSION}.zip
fi

# http://www.redminecrm.com/pages/redminecrm-theme
REDMINECRM_VERSION=0_0_2
if [ -f ${THEMES_SETUP_DIR}/redminecrm-${REDMINECRM_VERSION}.zip ]; then
  unzip ${THEMES_SETUP_DIR}/redminecrm-${REDMINECRM_VERSION}.zip -d ${THEMES_INSTALL_DIR}/
else
  wget http://www.redminecrm.com/license_manager/3834/redminecrm-${REDMINECRM_VERSION}.zip -P /tmp/
  unzip /tmp/redminecrm-${REDMINECRM_VERSION}.zip -d ${THEMES_INSTALL_DIR}/
  rm -rf /tmp/redminecrm-${REDMINECRM_VERSION}.zip
fi

# http://redminecrm.com/pages/highrise-theme
HIGHRISE_VERSION=1_1_2
if [ -f ${THEMES_SETUP_DIR}/highrise-${HIGHRISE_VERSION}.zip ]; then
  unzip ${THEMES_SETUP_DIR}/highrise-${HIGHRISE_VERSION}.zip -d ${THEMES_INSTALL_DIR}/
else
  wget http://redminecrm.com/license_manager/7646/highrise-${HIGHRISE_VERSION}.zip -P /tmp/
  unzip /tmp/highrise-${HIGHRISE_VERSION}.zip -d ${THEMES_INSTALL_DIR}/
  rm -rf /tmp/highrise-${HIGHRISE_VERSION}.zip
fi

# http://www.redminecrm.com/pages/circle-theme
CIRCLE_THEME_VERSION=1_0_1
if [ -f ${THEMES_SETUP_DIR}/circle_theme-${CIRCLE_THEME_VERSION}.zip ]; then
  unzip ${THEMES_SETUP_DIR}/circle_theme-${CIRCLE_THEME_VERSION}.zip -d ${THEMES_INSTALL_DIR}/
else
  wget http://www.redminecrm.com/license_manager/11619/circle_theme-${CIRCLE_THEME_VERSION}.zip -P /tmp/
  unzip /tmp/circle_theme-${CIRCLE_THEME_VERSION}.zip -d ${THEMES_INSTALL_DIR}/
  rm -rf /tmp/circle_theme-${CIRCLE_THEME_VERSION}.zip
fi

# https://github.com/makotokw/redmine-theme-gitmike
GITMIKE_VERSION=r6
mkdir -p ${THEMES_INSTALL_DIR}/gitmike
if [ -f ${THEMES_SETUP_DIR}/gitmike-${GITMIKE_VERSION}.tar.gz ]; then
  tar -zvxf ${THEMES_SETUP_DIR}/gitmike-${GITMIKE_VERSION}.tar.gz --strip=1 -C ${THEMES_INSTALL_DIR}/gitmike
else
  wget -nv https://github.com/makotokw/redmine-theme-gitmike/archive/${GITMIKE_VERSION}.tar.gz -O - | tar -zvxf - --strip=1 -C ${THEMES_INSTALL_DIR}/gitmike
fi
