#!/bin/bash

# export http_proxy=http://192.168.1.1:3128
# export ftp_proxy=http://192.168.1.1:3128

# install passenger
gem install --no-ri --no-rdoc passenger -v 3.0.21
passenger-install-apache2-module --auto
mod_passenger=$(find /usr/lib/ruby/gems/ -name mod_passenger.so)
if [ -n "${mod_passenger}" ]; then
	echo "LoadModule passenger_module ${mod_passenger}" > /etc/apache2/mods-available/passenger.load
	a2enmod passenger
else
  echo "ERROR: could not configure passenger module"
fi

cat >> /etc/apache2/apache2.conf <<EOF

PassengerRoot /usr/lib/ruby/gems/1.9.1/gems/passenger-3.0.21
PassengerRuby /usr/bin/ruby
PassengerDefaultUser www-data
PassengerMaxRequests 5000
EOF

cat > /etc/apache2/conf.d/redmine.conf <<EOF
<VirtualHost *:80>
  RailsEnv production
  DocumentRoot /redmine/public
  <Directory /redmine/public>
    AllowOverride all
    Options -MultiViews
  </Directory>
</VirtualHost>
EOF

# install redmine
mkdir -p /redmine
cd /redmine
wget "http://www.redmine.org/releases/redmine-2.3.3.tar.gz" -O - | tar -zvxf - --strip=1 -C /redmine

# install gems
bundle install --without postgresql

# add database.yml template
cat > config/database.yml <<EOF
production:
  adapter: mysql2
  database: {{DB_NAME}}
  host: {{DB_HOST}}
  username: {{DB_USER}}
  password: {{DB_PASS}}
  pool: {{DB_POOL}}
EOF

# install themes
. /redmine/setup/themes

# install plugins
. /redmine/setup/plugins

# finalize redmine installation
mkdir -p tmp tmp/pdf public/plugin_assets
chmod -R 755 files log public/plugin_assets
chmod -R 1777 tmp
chown -R www-data:www-data /redmine

cat > /etc/supervisor/conf.d/apache2.conf <<EOF
[program:apache2]
directory=/
command=/usr/sbin/apache2 -DFOREGROUND
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stderr_logfile=/var/log/supervisor/%(program_name)s_error.log
EOF
