#!/bin/bash

DB_HOST=${DB_HOST:-localhost}
DB_NAME=${DB_NAME:-redmine}
DB_USER=${DB_USER:-root}
DB_PASS=${DB_PASS:-}
DB_INIT=${DB_INIT:-no}

# start supervisord
/usr/bin/supervisord

if [ "${DB_HOST}" == "localhost" ]; then
DB_INIT="yes"
mysql_install_db --user=mysql
cat > /etc/supervisor/conf.d/mysqld.conf <<EOF
[program:mysqld]
priority=20
directory=/tmp
command=/usr/bin/mysqld_safe
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stderr_logfile=/var/log/supervisor/%(program_name)s.log
EOF
supervisorctl update
sleep 3
fi

chmod -R 755 /redmine/files
chown -R www-data:www-data /redmine/files

cd /redmine
sed 's/{{DB_HOST}}/'${DB_HOST}'/' -i config/database.yml
sed 's/{{DB_NAME}}/'${DB_NAME}'/' -i config/database.yml
sed 's/{{DB_USER}}/'${DB_USER}'/' -i config/database.yml
sed 's/{{DB_PASS}}/'${DB_PASS}'/' -i config/database.yml

if [ "${DB_INIT}" == "yes" ]; then
	# isolate the plugins
	mv plugins plugins-1
	RAILS_ENV=production rake db:create
	RAILS_ENV=production rake db:migrate
	mv plugins-1 plugins
	RAILS_ENV=production rake redmine:plugins:migrate
fi

rake generate_secret_token
touch tmp/restart.txt

tail -F /var/log/apache2/other_vhosts_access.log
