#!/bin/bash

DB_HOST=${DB_HOST:-localhost}
DB_NAME=${DB_NAME:-redmine_production}
DB_USER=${DB_USER:-root}
DB_PASS=${DB_PASS:-}
DB_POOL=${DB_POOL:-5}
DB_INIT=${DB_INIT:-no}

PASSENGER_MAX_POOL_SIZE=${PASSENGER_MAX_POOL_SIZE:-6}
PASSENGER_MIN_INSTANCES=${PASSENGER_MIN_INSTANCES:-1}
PASSENGER_MAX_REQUESTS=${PASSENGER_MAX_REQUESTS:-0}
PASSENGER_POOL_IDLE_TIME=${PASSENGER_POOL_IDLE_TIME:-300}

cat >> /etc/apache2/apache2.conf <<EOF

PassengerMaxPoolSize ${PASSENGER_MAX_POOL_SIZE}
PassengerMinInstances ${PASSENGER_MIN_INSTANCES}
PassengerMaxRequests ${PASSENGER_MAX_REQUESTS}
PassengerPoolIdleTime ${PASSENGER_POOL_IDLE_TIME}
EOF

# start supervisord
/usr/bin/supervisord

if [ "${DB_HOST}" == "localhost" ]; then
DB_INIT="yes"
mysql_install_db --user=mysql
	cat > /etc/supervisor/conf.d/mysqld.conf <<EOF
[program:mysqld]
priority=20
directory=/tmp
command=/usr/bin/mysqld_safe
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stderr_logfile=/var/log/supervisor/%(program_name)s.log
EOF
	supervisorctl update

	# wait for mysql server to start (max 120 seconds)
	timeout=120
	while ! mysqladmin -uroot ${DB_PASS:+-p$DB_PASS} status >/dev/null 2>&1
	do
		timeout=$(expr $timeout - 1)
		if [ $timeout -eq 0 ]; then
			echo "Failed to start mysql server"
			exit 1
		fi
		sleep 1
	done
fi

chmod 755 /redmine/files
chown www-data:www-data /redmine/files

cd /redmine
sudo -u www-data -H sed 's/{{DB_HOST}}/'${DB_HOST}'/' -i config/database.yml
sudo -u www-data -H sed 's/{{DB_NAME}}/'${DB_NAME}'/' -i config/database.yml
sudo -u www-data -H sed 's/{{DB_USER}}/'${DB_USER}'/' -i config/database.yml
sudo -u www-data -H sed 's/{{DB_PASS}}/'${DB_PASS}'/' -i config/database.yml
sudo -u www-data -H sed 's/{{DB_POOL}}/'${DB_POOL}'/' -i config/database.yml

if [ "${DB_INIT}" == "yes" ]; then
	# isolate the plugins
	sudo -u www-data -H mv plugins plugins-1
	sudo -u www-data -H RAILS_ENV=production rake db:create
	sudo -u www-data -H RAILS_ENV=production rake db:migrate
	sudo -u www-data -H mv plugins-1 plugins
	sudo -u www-data -H RAILS_ENV=production rake redmine:plugins:migrate
fi

sudo -u www-data -H rake generate_secret_token
sudo -u www-data -H touch tmp/restart.txt

tail -F /var/log/apache2/other_vhosts_access.log
