#!/bin/bash

# export http_proxy=http://192.168.1.1:3128
# export ftp_proxy=http://192.168.1.1:3128

# install passenger
gem install --no-ri --no-rdoc passenger -v 3.0.21
passenger-install-apache2-module --auto
mod_passenger=$(find /usr/lib/ruby/gems/ -name mod_passenger.so)
if [ -n "${mod_passenger}" ]; then
	echo "LoadModule passenger_module ${mod_passenger}" > /etc/apache2/mods-available/passenger.load
	a2enmod passenger
else
  echo "ERROR: could not configure passenger module"
  exit 1
fi

cat >> /etc/apache2/apache2.conf <<EOF

PassengerRoot /usr/lib/ruby/gems/1.9.1/gems/passenger-3.0.21
PassengerRuby /usr/bin/ruby
PassengerDefaultUser www-data
EOF

cat > /etc/apache2/conf.d/redmine.conf <<EOF
<VirtualHost *:80>
  RailsEnv production
  DocumentRoot /redmine/public
  <Directory /redmine/public>
    AllowOverride all
    Options -MultiViews
  </Directory>
</VirtualHost>
EOF

# install redmine
mkdir -p /redmine
cd /redmine
wget "http://www.redmine.org/releases/redmine-2.4.2.tar.gz" -O - | tar -zvxf - --strip=1 -C /redmine

# install gems
bundle install --without postgresql

# add database.yml template
sudo -u www-data -H cat > config/database.yml <<EOF
production:
  adapter: mysql2
  database: {{DB_NAME}}
  host: {{DB_HOST}}
  username: {{DB_USER}}
  password: {{DB_PASS}}
  pool: {{DB_POOL}}
EOF

# install themes
. /redmine/setup/themes

# install plugins
. /redmine/setup/plugins

# finalize redmine installation
mkdir -p tmp tmp/pdf public/plugin_assets
chmod -R 755 files log public/plugin_assets
chmod -R 1777 tmp
chown -R www-data:www-data /redmine

# setup log rotation for redmine
cat > /etc/logrotate.d/redmine <<EOF
/redmine/log/*.log {
    weekly
    missingok
    rotate 52
    compress
    delaycompress
    notifempty
    copytruncate
}
EOF

# setup log rotation for supervisord
cat > /etc/logrotate.d/supervisord <<EOF
/var/log/supervisor/*.log {
    weekly
    missingok
    rotate 52
    compress
    delaycompress
    notifempty
    copytruncate
}
EOF

cat > /etc/supervisor/conf.d/apache2.conf <<EOF
[program:apache2]
directory=/
command=/usr/sbin/apache2 -DFOREGROUND
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stderr_logfile=/var/log/supervisor/%(program_name)s_error.log
EOF

# configure supervisord to start cron
cat > /etc/supervisor/conf.d/cron.conf <<EOF
[program:cron]
priority=20
directory=/tmp
command=/usr/sbin/cron -f
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stderr_logfile=/var/log/supervisor/%(program_name)s.log
EOF
