#!/bin/bash

set -e

#
## Install tarballs
#

# redmine tweaks plugin
# wget https://github.com/alexandermeindl/redmine_tweaks/archive/master.tar.gz -O redmine_tweaks.tar.gz
mkdir -p /redmine/plugins/redmine_tweaks
if [ -f /redmine/setup/plugins/redmine_tweaks.tar.gz ]; then
	tar -zvxf /redmine/setup/plugins/redmine_tweaks.tar.gz --strip=1 -C /redmine/plugins/redmine_tweaks || exit 1
else
	wget https://github.com/alexandermeindl/redmine_tweaks/archive/master.tar.gz -O - | tar -zvxf - --strip=1 -C /redmine/plugins/redmine_tweaks
fi

# line numbers plugin
# wget https://github.com/cdwertmann/line_numbers/archive/master.tar.gz -O line_numbers.tar.gz
mkdir -p /redmine/plugins/line_numbers
if [ -f /redmine/setup/plugins/line_numbers.tar.gz ]; then
	tar -zvxf /redmine/setup/plugins/line_numbers.tar.gz --strip=1 -C /redmine/plugins/line_numbers || exit 1
else
	wget https://github.com/cdwertmann/line_numbers/archive/master.tar.gz -O - | tar -zvxf - --strip=1 -C /redmine/plugins/line_numbers
fi

# did you mean? plugin
# wget https://github.com/abahgat/redmine_didyoumean/archive/1.2.0.tar.gz -O redmine_didyoumean-1.2.0.tar.gz
mkdir -p /redmine/plugins/redmine_didyoumean
if [ -f /redmine/setup/plugins/redmine_didyoumean-1.2.0.tar.gz ]; then
	tar -zvxf /redmine/setup/plugins/redmine_didyoumean-1.2.0.tar.gz --strip=1 -C /redmine/plugins/redmine_didyoumean || exit 1
else
	wget https://github.com/abahgat/redmine_didyoumean/archive/1.2.0.tar.gz -O - | tar -zvxf - --strip=1 -C /redmine/plugins/redmine_didyoumean
fi

# redmine embed video plugin
# wget https://github.com/cforce/redmine_embedded_video/archive/master.tar.gz -O redmine_embedded_video.tar.gz
mkdir -p /redmine/plugins/redmine_embedded_video
if [ -f /redmine/setup/plugins/redmine_embedded_video.tar.gz ]; then
	tar -zvxf /redmine/setup/plugins/redmine_embedded_video.tar.gz --strip=1 -C /redmine/plugins/redmine_embedded_video || exit 1
else
	wget https://github.com/cforce/redmine_embedded_video/archive/master.tar.gz -O - | tar -zvxf - --strip=1 -C /redmine/plugins/redmine_embedded_video
fi

# redmine gist plugin
# wget https://github.com/dergachev/redmine_gist/archive/master.tar.gz -O redmine_gist.tar.gz
mkdir -p /redmine/plugins/redmine_gist
if [ -f /redmine/setup/plugins/redmine_gist.tar.gz ]; then
	tar -zvxf /redmine/setup/plugins/redmine_gist.tar.gz --strip=1 -C /redmine/plugins/redmine_gist || exit 1
else
	wget https://github.com/dergachev/redmine_gist/archive/master.tar.gz -O - | tar -zvxf - --strip=1 -C /redmine/plugins/redmine_gist
fi

# redmine tags plugin
# wget https://github.com/ixti/redmine_tags/archive/master.tar.gz -O redmine_tags.tar.gz
mkdir -p /redmine/plugins/redmine_tags
if [ -f /redmine/setup/plugins/redmine_tags.tar.gz ]; then
	tar -zvxf /redmine/setup/plugins/redmine_tags.tar.gz --strip=1 -C /redmine/plugins/redmine_tags || exit 1
else
	wget https://github.com/ixti/redmine_tags/archive/master.tar.gz -O - | tar -zvxf - --strip=1 -C /redmine/plugins/redmine_tags
fi

# issuefy plugin
# wget https://github.com/tchx84/issuefy/archive/master.tar.gz -O issuefy.tar.gz
mkdir -p /redmine/plugins/issuefy
if [ -f /redmine/setup/plugins/issuefy.tar.gz ]; then
	tar -zvxf /redmine/setup/plugins/issuefy.tar.gz --strip=1 -C /redmine/plugins/issuefy || exit 1
else
	wget https://github.com/tchx84/issuefy/archive/master.tar.gz -O - | tar -zvxf - --strip=1 -C /redmine/plugins/issuefy
fi
echo 'gem "spreadsheet", "0.8.5"' >> Gemfile

# open flash charts plugin
# wget https://github.com/pullmonkey/open_flash_chart/archive/master.tar.gz -O open_flash_chart.tar.gz
mkdir -p /redmine/plugins/open_flash_chart
if [ -f /redmine/setup/plugins/open_flash_chart.tar.gz ]; then
	tar -zvxf /redmine/setup/plugins/open_flash_chart.tar.gz --strip=1 -C /redmine/plugins/open_flash_chart || exit 1
else
	wget https://github.com/pullmonkey/open_flash_chart/archive/master.tar.gz -O - | tar -zvxf - --strip=1 -C /redmine/plugins/open_flash_chart
fi

mkdir -p /redmine/public/plugin_assets/open_flash_chart
cp -r /redmine/plugins/open_flash_chart/assets /redmine/public/plugin_assets/open_flash_chart

# redmine charts2 plugin
# wget https://github.com/pharmazone/redmine_charts2/archive/redmine21.tar.gz -O redmine_charts21.tar.gz
mkdir -p /redmine/plugins/redmine_charts2
if [ -f /redmine/setup/plugins/redmine_charts21.tar.gz ]; then
	tar -zvxf /redmine/setup/plugins/redmine_charts21.tar.gz --strip=1 -C /redmine/plugins/redmine_charts2 || exit 1
else
	wget https://github.com/pharmazone/redmine_charts2/archive/redmine21.tar.gz -O - | tar -zvxf - --strip=1 -C /redmine/plugins/redmine_charts2
fi

# redmine announcements plugin
# wget https://github.com/buoyant/redmine_announcements/archive/master.tar.gz -O redmine_announcements.tar.gz
mkdir -p /redmine/plugins/redmine_announcements
if [ -f /redmine/setup/plugins/redmine_announcements.tar.gz ]; then
	tar -zvxf /redmine/setup/plugins/redmine_announcements.tar.gz --strip=1 -C /redmine/plugins/redmine_announcements || exit 1
else
	wget https://github.com/buoyant/redmine_announcements/archive/master.tar.gz -O - | tar -zvxf - --strip=1 -C /redmine/plugins/redmine_announcements
fi

# remine recurring tasks
# wget https://github.com/nutso/redmine-plugin-recurring-tasks/archive/v.1.3.0.tar.gz -O recurring_tasks-1.3.0.tar.gz
mkdir -p /redmine/plugins/recurring_tasks
if [ -f /redmine/setup/plugins/recurring_tasks-1.3.0.tar.gz ]; then
	tar -zvxf /redmine/setup/plugins/recurring_tasks-1.3.0.tar.gz --strip=1 -C /redmine/plugins/recurring_tasks || exit 1
else
	wget https://github.com/nutso/redmine-plugin-recurring-tasks/archive/v1.3.0.tar.gz -O - | tar -zvxf - --strip=1 -C /redmine/plugins/recurring_tasks
fi

#
## Install zipped archives
#

# issue checklist plugin
# wget http://redminecrm.com/license_manager/4200/redmine_issue_checklist-2_0_5.zip -O redmine_issue_checklist-2_0_5.zip
if [ -f /redmine/setup/plugins/redmine_issue_checklist-2_0_5.zip ]; then
	unzip /redmine/setup/plugins/redmine_issue_checklist-2_0_5.zip -d /redmine/plugins/
else
	wget http://redminecrm.com/license_manager/4200/redmine_issue_checklist-2_0_5.zip -P /tmp/
	unzip /tmp/redmine_issue_checklist-2_0_5.zip -d /redmine/plugins/
	rm -rf /tmp/redmine_issue_checklist-2_0_5.zip
fi

# redmine people plugin
# wget http://redminecrm.com/license_manager/4122/redmine_people-0_1_6.zip -O redmine_people-0_1_6.zip
if [ -f /redmine/setup/plugins/redmine_people-0_1_6.zip ]; then
	unzip /redmine/setup/plugins/redmine_people-0_1_6.zip -d /redmine/plugins/
else
	wget http://redminecrm.com/license_manager/4122/redmine_people-0_1_6.zip -P /tmp/
	unzip /tmp/redmine_people-0_1_6.zip -d /redmine/plugins/
	rm -rf /tmp/redmine_people-0_1_6.zip
fi

# redmine code review plugin
# wget https://bitbucket.org/haru_iida/redmine_code_review/downloads/redmine_code_review-0.6.3.zip -O redmine_code_review-0.6.3.zip
if [ -f /redmine/setup/plugins/redmine_code_review-0.6.3.zip ]; then
	unzip /redmine/setup/plugins/redmine_code_review-0.6.3.zip -d /redmine/plugins/
else
	wget https://bitbucket.org/haru_iida/redmine_code_review/downloads/redmine_code_review-0.6.3.zip -P /tmp/
	unzip /tmp/redmine_code_review-0.6.3.zip -d /redmine/plugins/
	rm -rf /tmp/redmine_code_review-0.6.3.zip
fi

#
## Satisfy gem dependencies for plugins
#
bundle install --without development tests
