#!/bin/bash
set -e

REDMINE_VERSION=2.5.1

mkdir -p /redmine
cd /redmine

# install redmine, use local copy if available
if [ -f /redmine/setup/redmine-${REDMINE_VERSION}.tar.gz ]; then
  tar -zvxf /redmine/setup/redmine-${REDMINE_VERSION}.tar.gz --strip=1 -C /redmine
else
  wget "http://www.redmine.org/releases/redmine-${REDMINE_VERSION}.tar.gz" -O - | tar -zvxf - --strip=1 -C /redmine
fi

# install gems
echo 'gem "unicorn"' >> Gemfile
echo 'gem "fastercsv", "~> 1.5.0"' >> Gemfile
echo 'gem "yard"' >> Gemfile
echo 'gem "dalli", "~> 2.7.0"' >> Gemfile
if [ -d "/redmine/setup/cache" ]; then
  # offline gem installation
  mv /redmine/setup/cache vendor/
  bundle install --local --without development tests
else
  # online gem installation
  bundle install --without development tests
fi

cp config/database.yml.example config/database.yml

# install themes
. /redmine/setup/themes/install

# install plugins
. /redmine/setup/plugins/install

# finalize redmine installation
mkdir -p tmp tmp/pdf public/plugin_assets tmp/pids/ tmp/sockets/
chmod -R u+rwX files log tmp
chown -R www-data:www-data /redmine

# setup log rotation for redmine
cat > /etc/logrotate.d/redmine <<EOF
/redmine/log/*.log {
    weekly
    missingok
    rotate 52
    compress
    delaycompress
    notifempty
    copytruncate
}
EOF

# configure supervisord to start unicorn
cat > /etc/supervisor/conf.d/unicorn.conf <<EOF
[program:unicorn]
priority=20
directory=/redmine
command=bundle exec unicorn_rails -E production -c /redmine/config/unicorn.rb
user=root
autostart=false
autorestart=true
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stderr_logfile=/var/log/supervisor/%(program_name)s.log
EOF

# supervise mysql server start (manual)
cat > /etc/supervisor/conf.d/mysqld.conf <<EOF
[program:mysqld]
priority=20
directory=/tmp
command=/usr/bin/mysqld_safe
user=root
autostart=false
autorestart=true
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stderr_logfile=/var/log/supervisor/%(program_name)s.log
EOF

cat > /etc/supervisor/conf.d/memcached.conf <<EOF
[program:memcached]
priority=20
directory=/tmp
command=/usr/bin/memcached -m {{MEMCACHED_SIZE}}
user=www-data
autostart=false
autorestart=true
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stderr_logfile=/var/log/supervisor/%(program_name)s.log
EOF
