#!/bin/bash

DB_HOST=${DB_HOST:-localhost}
DB_PORT=${DB_PORT:-3306}
DB_NAME=${DB_NAME:-redmine_production.db}
DB_USER=${DB_USER:-root}
DB_PASS=${DB_PASS:-}
DB_POOL=${DB_POOL:-5}

MEMCACHED_SIZE=${MEMCACHED_SIZE:-64}

SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
SMTP_PORT=${SMTP_PORT:-587}
SMTP_USER=${SMTP_USER:-}
SMTP_PASS=${SMTP_PASS:-}

# generate a password for root.
ROOT_PASSWORD=$(pwgen -c -n -1 12)
echo "root:$ROOT_PASSWORD" | chpasswd
echo User: root Password: $ROOT_PASSWORD

# start supervisord
/usr/bin/supervisord

chmod 755 /redmine/files
chown www-data:www-data /redmine/files

cd /redmine
sudo -u www-data -H sed 's/{{DB_HOST}}/'${DB_HOST}'/' -i config/database.yml
sudo -u www-data -H sed 's/{{DB_PORT}}/'${DB_PORT}'/' -i config/database.yml
sudo -u www-data -H sed 's/{{DB_NAME}}/'${DB_NAME}'/' -i config/database.yml
sudo -u www-data -H sed 's/{{DB_USER}}/'${DB_USER}'/' -i config/database.yml
sudo -u www-data -H sed 's/{{DB_PASS}}/'${DB_PASS}'/' -i config/database.yml
sudo -u www-data -H sed 's/{{DB_POOL}}/'${DB_POOL}'/' -i config/database.yml

# start memcached and install config if ${MEMCACHED_SIZE} is not 0
if [ "${MEMCACHED_SIZE}" != "0" ]; then
	sed 's/{{MEMCACHED_SIZE}}/'${MEMCACHED_SIZE}'/' -i /etc/supervisor/conf.d/memcached.conf
	supervisorctl update
	supervisorctl start memcached
	sudo -u www-data -H sed 's/{{ENABLE_CACHE}}/true/' -i config/additional_environment.rb
else
	sudo -u www-data -H sed 's/{{ENABLE_CACHE}}/false/' -i config/additional_environment.rb
fi

# configure mail delivery
if [ -n "${SMTP_HOST}" -a -n "${SMTP_USER}" -a -n "${SMTP_PASS}" ]; then
	cat >> config/configuration.yml <<EOF

default:
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      address: ${SMTP_HOST}
      port: ${SMTP_PORT}
      authentication: :login
      user_name: "${SMTP_USER}"
      password: "${SMTP_PASS}"
EOF
	chown www-data:www-data config/configuration.yml
fi

appDbMigrate () {
	# isolate the plugins
	mv plugins plugins-1
	RAILS_ENV=production rake db:create
	RAILS_ENV=production rake db:migrate
	mv plugins-1 plugins
	RAILS_ENV=production rake redmine:plugins:migrate
	RAILS_ENV=production rake tmp:cache:clear
	RAILS_ENV=production rake tmp:sessions:clear
}

appStart () {
	appDbMigrate

	RAILS_ENV=production rake generate_secret_token

    RAILS_ENV=production unicorn -D -l 0.0.0.0:9000

	tail -F /redmine/log/production.log
}

appHelp () {
	echo "Available options:"
	echo " app:start          - Starts the redmine server (default)"
	echo " app:db:migrate     - Migrate the database."
	echo " app:help           - Displays the help"
	echo " [command]          - Execute the specified linux command eg. bash."
}

case "$1" in
	app:start)
		appStart
		;;
	app:db:migrate)
		appDbMigrate
		;;
	app:help)
		appHelp
		;;
	*)
		if [ -x $1 ]; then
			$1
		else
			prog=$(which $1)
			if [ -n "${prog}" ] ; then
				shift 1
				$prog $@
			else
				appHelp
			fi
		fi
		;;
esac

exit 0
