#!/bin/bash

# http://redminecrm.com/pages/a1-theme
unzip /redmine/setup/themes/a1-1_1_2.zip -d /redmine/public/themes/

# http://www.redminecrm.com/pages/coffee-theme
unzip /redmine/setup/themes/coffee-0_0_4.zip -d /redmine/public/themes/

# http://www.redminecrm.com/pages/redminecrm-theme
unzip /redmine/setup/themes/redminecrm-0_0_2.zip -d /redmine/public/themes/

# http://redminecrm.com/pages/highrise-theme
unzip /redmine/setup/themes/highrise-1_1_2.zip -d /redmine/public/themes/

# https://github.com/makotokw/redmine-theme-gitmike
mkdir -p /redmine/public/themes/gitmike
tar -zvxf /redmine/setup/themes/gitmike-r6.tar.gz --strip=1 -C /redmine/public/themes/gitmike
