#!/bin/bash

set -e

#
## Install tarballs
#

# redmine tweaks plugin
# wget https://github.com/alexandermeindl/redmine_tweaks/archive/master.tar.gz -O redmine_tweaks.tar.gz
mkdir -p /redmine/plugins/redmine_tweaks
tar -zvxf /redmine/setup/plugins/redmine_tweaks.tar.gz --strip=1 -C /redmine/plugins/redmine_tweaks

# line numbers plugin
# wget https://github.com/cdwertmann/line_numbers/archive/master.tar.gz -O line_numbers.tar.gz
mkdir -p /redmine/plugins/line_numbers
tar -zvxf /redmine/setup/plugins/line_numbers.tar.gz --strip=1 -C /redmine/plugins/line_numbers

# did you mean? plugin
# wget https://github.com/abahgat/redmine_didyoumean/archive/1.2.0.tar.gz -O redmine_didyoumean-1.2.0.tar.gz
mkdir -p /redmine/plugins/redmine_didyoumean
tar -zvxf /redmine/setup/plugins/redmine_didyoumean-1.2.0.tar.gz --strip=1 -C /redmine/plugins/redmine_didyoumean

# redmine embed video plugin
# wget https://github.com/cforce/redmine_embedded_video/archive/master.tar.gz -O redmine_embedded_video.tar.gz
mkdir -p /redmine/plugins/redmine_embedded_video
tar -zvxf /redmine/setup/plugins/redmine_embedded_video.tar.gz --strip=1 -C /redmine/plugins/redmine_embedded_video

# redmine gist plugin
# wget https://github.com/dergachev/redmine_gist/archive/master.tar.gz -O redmine_gist.tar.gz
mkdir -p /redmine/plugins/redmine_gist
tar -zvxf /redmine/setup/plugins/redmine_gist.tar.gz --strip=1 -C /redmine/plugins/redmine_gist

# redmine tags plugin
# wget https://github.com/ixti/redmine_tags/archive/master.tar.gz -O redmine_tags.tar.gz
mkdir -p /redmine/plugins/redmine_tags
tar -zvxf /redmine/setup/plugins/redmine_tags.tar.gz --strip=1 -C /redmine/plugins/redmine_tags

# issuefy plugin
# wget https://github.com/tchx84/issuefy/archive/master.tar.gz -O issuefy.tar.gz
mkdir -p /redmine/plugins/issuefy
tar -zvxf /redmine/setup/plugins/issuefy.tar.gz --strip=1 -C /redmine/plugins/issuefy
echo 'gem "spreadsheet", "0.8.5"' >> Gemfile

# open flash charts plugin
# wget https://github.com/pullmonkey/open_flash_chart/archive/master.tar.gz -O open_flash_chart.tar.gz
mkdir -p /redmine/plugins/open_flash_chart
tar -zvxf /redmine/setup/plugins/open_flash_chart.tar.gz --strip=1 -C /redmine/plugins/open_flash_chart

mkdir -p /redmine/public/plugin_assets/open_flash_chart
cp -r /redmine/plugins/open_flash_chart/assets/* /redmine/public/plugin_assets/open_flash_chart

# redmine charts2 plugin
# wget https://github.com/pharmazone/redmine_charts2/archive/redmine21.tar.gz -O redmine_charts21.tar.gz
mkdir -p /redmine/plugins/redmine_charts2
tar -zvxf /redmine/setup/plugins/redmine_charts21.tar.gz --strip=1 -C /redmine/plugins/redmine_charts2

# redmine announcements plugin
# wget https://github.com/buoyant/redmine_announcements/archive/master.tar.gz -O redmine_announcements.tar.gz
mkdir -p /redmine/plugins/redmine_announcements
tar -zvxf /redmine/setup/plugins/redmine_announcements.tar.gz --strip=1 -C /redmine/plugins/redmine_announcements

# redmine recurring tasks
# wget https://github.com/nutso/redmine-plugin-recurring-tasks/archive/v.1.3.0.tar.gz -O recurring_tasks-1.3.0.tar.gz
mkdir -p /redmine/plugins/recurring_tasks
tar -zvxf /redmine/setup/plugins/recurring_tasks-1.3.0.tar.gz --strip=1 -C /redmine/plugins/recurring_tasks

# redmine dashboard tasks
# wget https://github.com/jgraichen/redmine_dashboard/archive/v2.2.1.tar.gz -O redmine_dashboard-2.2.1.tar.gz
mkdir -p /redmine/plugins/redmine_dashboard
tar -zvxf /redmine/setup/plugins/redmine_dashboard-2.2.1.tar.gz --strip=1 -C /redmine/plugins/redmine_dashboard
echo 'gem "guard-rspec"' >> Gemfile

#
## Install zipped archives
#

# issue checklist plugin
# wget http://redminecrm.com/license_manager/4200/redmine_issue_checklist-2_0_5.zip -O redmine_issue_checklist-2_0_5.zip
unzip /redmine/setup/plugins/redmine_issue_checklist-2_0_5.zip -d /redmine/plugins/

# redmine people plugin
# wget http://redminecrm.com/license_manager/4122/redmine_people-0_1_6.zip -O redmine_people-0_1_6.zip
unzip /redmine/setup/plugins/redmine_people-0_1_6.zip -d /redmine/plugins/

# redmine code review plugin
# wget https://bitbucket.org/haru_iida/redmine_code_review/downloads/redmine_code_review-0.6.3.zip -O redmine_code_review-0.6.3.zip
unzip /redmine/setup/plugins/redmine_code_review-0.6.3.zip -d /redmine/plugins/

# redmine agile plugin
# wget http://redminecrm.com/license_manager/11099/redmine_agile-1_0_1-light.zip -O redmine_agile-1_0_1-light.zip
unzip /redmine/setup/plugins/redmine_agile-1_0_1-light.zip -d /redmine/plugins/

#
## Satisfy gem dependencies for plugins
#

bundle install --without development tests
